services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airlipay
    container_name: postgres
    volumes:
      - /home/techarcgram/pgdata:/var/lib/postgresql/data
    networks:
      - postgres_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    container_name: airlipay-api
    env_file:
      - ../../.env
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    volumes:
      - /home/techarcgram/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
