pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'

    }
    stages {
        stage('Build') {
            steps {
                sh 'node --version'
                sh 'yarn install'
                sh 'yarn run build'
            }
        }
        // stage('Test') {
        //     steps {
        //         sh './jenkins/scripts/test.sh'
        //     }
        // }
        stage('Deliver') {
            steps {
                sh 'yarn run start:dev'
            }
        }
    }
}