pipeline {
    agent any
    environment {
        CI = 'true'

    }
    stages {
        stage('Build') {
            steps {
                sh 'docker compose -f docker/production/docker-compose.yml build'
            }
        }
        stage('Deliver') {
            steps {
                sh 'docker compose -f docker/production/docker-compose.yml up --remove-orphans
 --force-recreate'
            }
        }
    }
}